name: CI/CD MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow numpy pandas scikit-learn lightgbm joblib dagshub

      - name: Run MLflow project
        working-directory: ./MLProject  
        run: |
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        id: get-run-id
        run: |
          RUN_ID=$(ls -td ./mlruns/0/*/ | head -n 1 | cut -d'/' -f4)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Image
        run: |
          mlflow models build-docker \
            --model-uri "mlruns/0/${{ steps.get-run-id.outputs.run_id }}/artifacts/model" \
            --name diamond-model

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag diamond-model ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:latest