name: CI/CD MLflow Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MLFLOW_TRACKING_URI: ./mlruns
  EXPERIMENT_NAME: "diamond-price-prediction"

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      # Install dependencies
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.11.3 numpy pandas scikit-learn lightgbm joblib dagshub docker

      # Run MLflow training
      - name: Train model with MLflow
        working-directory: ./MLProject
        run: |
          # Generate unique run ID
          export MLFLOW_RUN_ID=$(python -c "import uuid; print(uuid.uuid4().hex)")
          
          # Run with explicit experiment name
          mlflow run . \
            --env-manager=local \
            --experiment-name="$EXPERIMENT_NAME" \
            --no-conda

      # Get the latest run ID
      - name: Extract run ID
        id: get-run-id
        run: |
          RUN_ID=$(ls -t mlruns/0/*/ | head -n1 | cut -d'/' -f3)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Model URI: mlruns/0/$RUN_ID/artifacts/model"

      # Build Docker image
      - name: Build Docker container
        run: |
          mlflow models build-docker \
            --model-uri "mlruns/0/${{ steps.get-run-id.outputs.run_id }}/artifacts/model" \
            --name "diamond-model" \
            --enable-mlserver

      # Login to Docker Hub
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Push Docker image
      - name: Push to Docker Hub
        run: |
          docker tag diamond-model ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:latest
          docker tag diamond-model ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:${{ steps.get-run-id.outputs.run_id }}
          
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:${{ steps.get-run-id.outputs.run_id }}

      # (Optional) Save artifacts
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: model-artifacts
          path: |
            mlruns/0/${{ steps.get-run-id.outputs.run_id }}/artifacts/*
          retention-days: 1