name: CI/CD MLflow with Docker Fix

on:
  push:
    branches: [main]

jobs:
  mlflow-docker:
    runs-on: ubuntu-latest
    env:
      MODEL_NAME: diamond-model
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mlflow==2.11.3 docker

      - name: Run MLflow training
        run: |
          mlflow run ./MLProject --env-manager=local --no-conda

      - name: Prepare Docker artifacts
        id: docker-prep
        run: |
          RUN_ID=$(ls -t ./mlruns/0/ | head -n1)
          MODEL_URI="mlruns/0/$RUN_ID/artifacts/model"
          echo "MODEL_URI=$MODEL_URI" >> $GITHUB_ENV
          echo "DOCKER_TAG=${DOCKER_USER}/${MODEL_NAME}:${RUN_ID}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          mlflow models build-docker \
            --model-uri "$MODEL_URI" \
            --name "$MODEL_NAME" \
            --enable-mlserver

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag $MODEL_NAME $DOCKER_TAG
          docker push $DOCKER_TAG
          docker tag $MODEL_NAME ${DOCKER_USER}/${MODEL_NAME}:latest
          docker push ${DOCKER_USER}/${MODEL_NAME}:latest