name: CI/CD MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow numpy pandas scikit-learn lightgbm joblib dagshub

      # Run MLflow project
      - name: Run MLflow project
        run: |
          mlflow run MLproject --env-manager=local 

      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)  # Tidak perlu menambahkan folder repo lagi
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Build Docker image from model
      - name: Build Docker Image from MLflow model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name diamond-model

      # Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag diamond-model ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:latest

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:latest