name: CI/CD MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Check Env
      - name: Check Env
        run: |
          echo "Python version: $(python --version)"
          echo "Current directory: $(pwd)"
          ls -la

      # 4. Install dependencies (umum)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub

      # 5. Run MLflow project
      - name: Run MLflow project
        run: |
          mlflow run MLProject --env-manager=local 

      # 6. Get latest MLflow run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # 7. Install Python dependencies (khusus model)
      - name: Install Python dependencies
        run: |
          pip install numpy pandas scikit-learn lightgbm joblib

      # 8. Upload model artifacts to GitHub
      - name: Upload model artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns/0/${{ env.RUN_ID }}/artifacts/model

      # 9. Build Docker image from MLflow model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name diamond-model

      # 10. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 11. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag diamond-model ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:latest

      # 12. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diamond-model:latest